default: &default_pg
  adapter: postgresql
  encoding: unicode
  pool: 15
  username: postgres
  password: test

development:
  <<: *default_pg
  database: pg_dev
#
# production:
#   <<: *default_pg
#   database: pg_prod
#   username: Rocket_Elevators_Information_System
#   password: <%= ENV['ROCKET_ELEVATORS_INFORMATION_SYSTEM_DATABASE_PASSWORD'] %>

